server {
    listen 80 default_server;
    server_name _;

    # Docker DNS (required when using a variable in fastcgi_pass)
    resolver 127.0.0.11 ipv6=off valid=30s;

    client_max_body_size 20m;
    keepalive_timeout 65;

    # Health
    location = /healthz {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    # ---------- EVERYTHING ELSE -> PHP-FPM ----------
    location / {
        include /etc/nginx/includes/php_fastcgi.conf;
        fastcgi_param REQUEST_URI $request_uri;

        set $fidget_fpm fidget-service:9000;
        fastcgi_pass $fidget_fpm;
    }
}
